development:
  username: root
  adapter: mysql
  database: picnic_development
  host: localhost
  password: ''
test:
  username: root
  adapter: mysql
  database: picnic_test
  host: localhost
  password: ''
production: 
  username: root
  adapter: mysql
  database: picnic_production
  host: localhost
  password: ''

