development:
  username: root
  adapter: mysql
  database: vcorp_development
  host: localhost
  password: ''
test:
  username: root
  adapter: mysql
  database: vcorp_test
  host: localhost
  password: ''
production: 
  username: root
  adapter: mysql
  database: vcorp_production
  host: localhost
  password: ''

